title: Party piñata
hero_image: images/banner.png
description: explore-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Swing a piñata
  - title: Hit the piñata
    completion: engaged
  - title: Use a stick
  - title: Create a message
  - title: Add some treats
    completion: internal
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - title: Upgrade your project