title: Party piñata
hero_image: images/banner.png
description: explore-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Start the party
  - title: Hit the piñata
    completion: engaged
  - title: Use a stick
  - title: Create a message
  - title: Add some treats
    completion: internal
  - title: Share your project
    completion: external
  - title: Upgrade your project
